# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software: you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

from quant_flash_attn_paramset_common import expand_paramset_to_cases

# HIF8 (quant_mode=0) tiling config 锁定 DAligned128: head_dim 仅支持 128
# BSND/BNSD 用例采用各 batch 等长 (seqused == max_seqlen), 避免非 TND 的 padding 行为差异
TEST_PARAMS = {
    # ============================== TND ==============================
    "TND_B1_QS4_KVS1024_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 4]],
        "cu_seqlens_kv": [[0, 1024]],
        "seqused_q": [[4]],
        "seqused_kv": [[1024]],
        "max_seqlen_q": [4],
        "max_seqlen_kv": [1024],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS3_KVS640_Nq1_Nkv1_D128_SP0": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 3]],
        "cu_seqlens_kv": [[0, 640]],
        "seqused_q": [[3]],
        "seqused_kv": [[640]],
        "max_seqlen_q": [3],
        "max_seqlen_kv": [640],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [False],
    },
    "TND_B1_QS128_KVS2048_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 128]],
        "cu_seqlens_kv": [[0, 2048]],
        "seqused_q": [[128]],
        "seqused_kv": [[2048]],
        "max_seqlen_q": [128],
        "max_seqlen_kv": [2048],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS512_KVS5120_Nq80_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [80],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 512]],
        "cu_seqlens_kv": [[0, 5120]],
        "seqused_q": [[512]],
        "seqused_kv": [[5120]],
        "max_seqlen_q": [512],
        "max_seqlen_kv": [5120],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS10_KVS128_Nq2_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [2],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 10]],
        "cu_seqlens_kv": [[0, 128]],
        "seqused_q": [[10]],
        "seqused_kv": [[128]],
        "max_seqlen_q": [10],
        "max_seqlen_kv": [128],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS699_KVS777_Nq64_Nkv2_D128_SP0": {
        "B": [1],
        "N_q": [64],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 699]],
        "cu_seqlens_kv": [[0, 777]],
        "seqused_q": [[699]],
        "seqused_kv": [[777]],
        "max_seqlen_q": [699],
        "max_seqlen_kv": [777],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS1_KVS1100_Nq32_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [32],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_kv": [[0, 1100]],
        "seqused_q": [[1]],
        "seqused_kv": [[1100]],
        "max_seqlen_q": [1],
        "max_seqlen_kv": [1100],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS3000_KVS6000_Nq16_Nkv8_D128_SP3": {
        "B": [1],
        "N_q": [16],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 3000]],
        "cu_seqlens_kv": [[0, 6000]],
        "seqused_q": [[3000]],
        "seqused_kv": [[6000]],
        "max_seqlen_q": [3000],
        "max_seqlen_kv": [6000],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS768_KVS5504_Nq56_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [56],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 768]],
        "cu_seqlens_kv": [[0, 5504]],
        "seqused_q": [[768]],
        "seqused_kv": [[5504]],
        "max_seqlen_q": [768],
        "max_seqlen_kv": [5504],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [False],
    },
    "TND_B1_QS2_KVS640_Nq56_Nkv4_D128_SP0": {
        "B": [1],
        "N_q": [56],
        "N_kv": [4],
        "D": [128],
        "cu_seqlens_q": [[0, 2]],
        "cu_seqlens_kv": [[0, 640]],
        "seqused_q": [[2]],
        "seqused_kv": [[640]],
        "max_seqlen_q": [2],
        "max_seqlen_kv": [640],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [256.0],
        "enable_lse": [False],
    },
    "TND_B3_QS1_KVS999_Nq256_Nkv4_D128_SP3": {
        "B": [3],
        "N_q": [256],
        "N_kv": [4],
        "D": [128],
        "cu_seqlens_q": [[0, 1, 2, 4]],
        "cu_seqlens_kv": [[0, 999, 2215, 3047]],
        "seqused_q": [[1, 1, 2]],
        "seqused_kv": [[999, 1216, 832]],
        "max_seqlen_q": [2],
        "max_seqlen_kv": [1216],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
    },
    "TND_B1_QS600_KVS500_Nq16_Nkv8_D128_SP0": {
        "B": [1],
        "N_q": [16],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 600]],
        "cu_seqlens_kv": [[0, 500]],
        "seqused_q": [[600]],
        "seqused_kv": [[500]],
        "max_seqlen_q": [600],
        "max_seqlen_kv": [500],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B2_QS900_KVS1500_Nq96_Nkv16_D128_SP3": {
        "B": [2],
        "N_q": [96],
        "N_kv": [16],
        "D": [128],
        "cu_seqlens_q": [[0, 900, 1966]],
        "cu_seqlens_kv": [[0, 1500, 3427]],
        "seqused_q": [[900, 1066]],
        "seqused_kv": [[1500, 1927]],
        "max_seqlen_q": [1066],
        "max_seqlen_kv": [1927],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [128.0],
        "enable_lse": [False],
    },
    "TND_B1_QS2000_KVS320_Nq4_Nkv1_D128_SP0": {
        "B": [1],
        "N_q": [4],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 2000]],
        "cu_seqlens_kv": [[0, 320]],
        "seqused_q": [[2000]],
        "seqused_kv": [[320]],
        "max_seqlen_q": [2000],
        "max_seqlen_kv": [320],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS3_KVS768_Nq16_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [16],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 3]],
        "cu_seqlens_kv": [[0, 768]],
        "seqused_q": [[3]],
        "seqused_kv": [[768]],
        "max_seqlen_q": [3],
        "max_seqlen_kv": [768],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
    },
    "TND_B1_QS4032_KVS2048_Nq8_Nkv8_D128_SP3": {
        "B": [1],
        "N_q": [8],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 4032]],
        "cu_seqlens_kv": [[0, 2048]],
        "seqused_q": [[4032]],
        "seqused_kv": [[2048]],
        "max_seqlen_q": [4032],
        "max_seqlen_kv": [2048],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [256.0],
        "enable_lse": [False],
    },
    "TND_B1_QS5_KVS3072_Nq32_Nkv2_D128_SP0": {
        "B": [1],
        "N_q": [32],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 5]],
        "cu_seqlens_kv": [[0, 3072]],
        "seqused_q": [[5]],
        "seqused_kv": [[3072]],
        "max_seqlen_q": [5],
        "max_seqlen_kv": [3072],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [False],
    },
    "TND_B1_QS1_KVS1_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_kv": [[0, 1]],
        "seqused_q": [[1]],
        "seqused_kv": [[1]],
        "max_seqlen_q": [1],
        "max_seqlen_kv": [1],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
    },
    "TND_B1_QS128_KVS128_Nq8_Nkv8_D128_SP3": {
        "B": [1],
        "N_q": [8],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 128]],
        "cu_seqlens_kv": [[0, 128]],
        "seqused_q": [[128]],
        "seqused_kv": [[128]],
        "max_seqlen_q": [128],
        "max_seqlen_kv": [128],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
    },
    "TND_B2_QS50_66_KVS100_120_Nq4_Nkv2_D128_SP3": {
        "B": [2],
        "N_q": [4],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 50, 116]],
        "cu_seqlens_kv": [[0, 100, 220]],
        "seqused_q": [[50, 66]],
        "seqused_kv": [[100, 120]],
        "max_seqlen_q": [66],
        "max_seqlen_kv": [120],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B3_QS8_16_32_KVS64_128_256_Nq16_Nkv4_D128_SP0": {
        "B": [3],
        "N_q": [16],
        "N_kv": [4],
        "D": [128],
        "cu_seqlens_q": [[0, 8, 24, 56]],
        "cu_seqlens_kv": [[0, 64, 192, 448]],
        "seqused_q": [[8, 16, 32]],
        "seqused_kv": [[64, 128, 256]],
        "max_seqlen_q": [32],
        "max_seqlen_kv": [256],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
    },
    "TND_B1_QS256_KVS1024_Nq48_Nkv8_D128_SP3": {
        "B": [1],
        "N_q": [48],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 256]],
        "cu_seqlens_kv": [[0, 1024]],
        "seqused_q": [[256]],
        "seqused_kv": [[1024]],
        "max_seqlen_q": [256],
        "max_seqlen_kv": [1024],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B5_QS1_KVS999_Nq8_Nkv1_D128_SP3": {
        "B": [5],
        "N_q": [8],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 1, 2, 3, 4, 5]],
        "cu_seqlens_kv": [[0, 999, 1998, 2997, 3996, 4995]],
        "seqused_q": [[1, 1, 1, 1, 1]],
        "seqused_kv": [[999, 999, 999, 999, 999]],
        "max_seqlen_q": [1],
        "max_seqlen_kv": [999],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS1000_KVS1000_Nq64_Nkv16_D128_SP0": {
        "B": [1],
        "N_q": [64],
        "N_kv": [16],
        "D": [128],
        "cu_seqlens_q": [[0, 1000]],
        "cu_seqlens_kv": [[0, 1000]],
        "seqused_q": [[1000]],
        "seqused_kv": [[1000]],
        "max_seqlen_q": [1000],
        "max_seqlen_kv": [1000],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
    },
    "TND_B2_QS333_777_KVS512_1024_Nq32_Nkv4_D128_SP3": {
        "B": [2],
        "N_q": [32],
        "N_kv": [4],
        "D": [128],
        "cu_seqlens_q": [[0, 333, 1110]],
        "cu_seqlens_kv": [[0, 512, 1536]],
        "seqused_q": [[333, 777]],
        "seqused_kv": [[512, 1024]],
        "max_seqlen_q": [777],
        "max_seqlen_kv": [1024],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
    },
    "TND_B1_QS2_KVS640_Nq1_Nkv1_D128_SP0": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 2]],
        "cu_seqlens_kv": [[0, 640]],
        "seqused_q": [[2]],
        "seqused_kv": [[640]],
        "max_seqlen_q": [2],
        "max_seqlen_kv": [640],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [True],
    },
    # ============================== BSND ==============================
    "BSND_B1_QS4_KVS1024_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 4]],
        "cu_seqlens_kv": [[0, 1024]],
        "seqused_q": [[4]],
        "seqused_kv": [[1024]],
        "max_seqlen_q": [4],
        "max_seqlen_kv": [1024],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BSND"],
    },
    "BSND_B1_QS3_KVS640_Nq1_Nkv1_D128_SP0": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 3]],
        "cu_seqlens_kv": [[0, 640]],
        "seqused_q": [[3]],
        "seqused_kv": [[640]],
        "max_seqlen_q": [3],
        "max_seqlen_kv": [640],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [True],
        "input_layout": ["BSND"],
    },
    "BSND_B1_QS128_KVS2048_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 128]],
        "cu_seqlens_kv": [[0, 2048]],
        "seqused_q": [[128]],
        "seqused_kv": [[2048]],
        "max_seqlen_q": [128],
        "max_seqlen_kv": [2048],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BSND"],
    },
    "BSND_B1_QS10_KVS128_Nq2_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [2],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 10]],
        "cu_seqlens_kv": [[0, 128]],
        "seqused_q": [[10]],
        "seqused_kv": [[128]],
        "max_seqlen_q": [10],
        "max_seqlen_kv": [128],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BSND"],
    },
    "BSND_B1_QS699_KVS777_Nq64_Nkv2_D128_SP0": {
        "B": [1],
        "N_q": [64],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 699]],
        "cu_seqlens_kv": [[0, 777]],
        "seqused_q": [[699]],
        "seqused_kv": [[777]],
        "max_seqlen_q": [699],
        "max_seqlen_kv": [777],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BSND"],
    },
    "BSND_B1_QS1_KVS1100_Nq32_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [32],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_kv": [[0, 1100]],
        "seqused_q": [[1]],
        "seqused_kv": [[1100]],
        "max_seqlen_q": [1],
        "max_seqlen_kv": [1100],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BSND"],
    },
    "BSND_B1_QS600_KVS500_Nq16_Nkv8_D128_SP0": {
        "B": [1],
        "N_q": [16],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 600]],
        "cu_seqlens_kv": [[0, 500]],
        "seqused_q": [[600]],
        "seqused_kv": [[500]],
        "max_seqlen_q": [600],
        "max_seqlen_kv": [500],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BSND"],
    },
    "BSND_B2_QS100_KVS200_Nq8_Nkv4_D128_SP3": {
        "B": [2],
        "N_q": [8],
        "N_kv": [4],
        "D": [128],
        "cu_seqlens_q": [[0, 100, 200]],
        "cu_seqlens_kv": [[0, 200, 400]],
        "seqused_q": [[100, 100]],
        "seqused_kv": [[200, 200]],
        "max_seqlen_q": [100],
        "max_seqlen_kv": [200],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BSND"],
    },
    "BSND_B4_QS64_KVS256_Nq4_Nkv2_D128_SP0": {
        "B": [4],
        "N_q": [4],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 64, 128, 192, 256]],
        "cu_seqlens_kv": [[0, 256, 512, 768, 1024]],
        "seqused_q": [[64, 64, 64, 64]],
        "seqused_kv": [[256, 256, 256, 256]],
        "max_seqlen_q": [64],
        "max_seqlen_kv": [256],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [True],
        "input_layout": ["BSND"],
    },
    "BSND_B1_QS2000_KVS320_Nq4_Nkv1_D128_SP0": {
        "B": [1],
        "N_q": [4],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 2000]],
        "cu_seqlens_kv": [[0, 320]],
        "seqused_q": [[2000]],
        "seqused_kv": [[320]],
        "max_seqlen_q": [2000],
        "max_seqlen_kv": [320],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BSND"],
    },
    "BSND_B3_QS32_KVS64_Nq8_Nkv8_D128_SP3": {
        "B": [3],
        "N_q": [8],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 32, 64, 96]],
        "cu_seqlens_kv": [[0, 64, 128, 192]],
        "seqused_q": [[32, 32, 32]],
        "seqused_kv": [[64, 64, 64]],
        "max_seqlen_q": [32],
        "max_seqlen_kv": [64],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BSND"],
    },
    "BSND_B1_QS512_KVS1024_Nq56_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [56],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 512]],
        "cu_seqlens_kv": [[0, 1024]],
        "seqused_q": [[512]],
        "seqused_kv": [[1024]],
        "max_seqlen_q": [512],
        "max_seqlen_kv": [1024],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BSND"],
    },
    # ============================== BNSD ==============================
    "BNSD_B1_QS4_KVS1024_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 4]],
        "cu_seqlens_kv": [[0, 1024]],
        "seqused_q": [[4]],
        "seqused_kv": [[1024]],
        "max_seqlen_q": [4],
        "max_seqlen_kv": [1024],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BNSD"],
    },
    "BNSD_B1_QS3_KVS640_Nq1_Nkv1_D128_SP0": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 3]],
        "cu_seqlens_kv": [[0, 640]],
        "seqused_q": [[3]],
        "seqused_kv": [[640]],
        "max_seqlen_q": [3],
        "max_seqlen_kv": [640],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [15.0],
        "enable_lse": [False],
        "input_layout": ["BNSD"],
    },
    "BNSD_B1_QS128_KVS2048_Nq1_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [1],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 128]],
        "cu_seqlens_kv": [[0, 2048]],
        "seqused_q": [[128]],
        "seqused_kv": [[2048]],
        "max_seqlen_q": [128],
        "max_seqlen_kv": [2048],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BNSD"],
    },
    "BNSD_B1_QS10_KVS128_Nq2_Nkv1_D128_SP3": {
        "B": [1],
        "N_q": [2],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 10]],
        "cu_seqlens_kv": [[0, 128]],
        "seqused_q": [[10]],
        "seqused_kv": [[128]],
        "max_seqlen_q": [10],
        "max_seqlen_kv": [128],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BNSD"],
    },
    "BNSD_B1_QS699_KVS777_Nq64_Nkv2_D128_SP0": {
        "B": [1],
        "N_q": [64],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 699]],
        "cu_seqlens_kv": [[0, 777]],
        "seqused_q": [[699]],
        "seqused_kv": [[777]],
        "max_seqlen_q": [699],
        "max_seqlen_kv": [777],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BNSD"],
    },
    "BNSD_B1_QS1_KVS1100_Nq32_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [32],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_kv": [[0, 1100]],
        "seqused_q": [[1]],
        "seqused_kv": [[1100]],
        "max_seqlen_q": [1],
        "max_seqlen_kv": [1100],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BNSD"],
    },
    "BNSD_B1_QS600_KVS500_Nq16_Nkv8_D128_SP0": {
        "B": [1],
        "N_q": [16],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 600]],
        "cu_seqlens_kv": [[0, 500]],
        "seqused_q": [[600]],
        "seqused_kv": [[500]],
        "max_seqlen_q": [600],
        "max_seqlen_kv": [500],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BNSD"],
    },
    "BNSD_B2_QS100_KVS200_Nq8_Nkv4_D128_SP3": {
        "B": [2],
        "N_q": [8],
        "N_kv": [4],
        "D": [128],
        "cu_seqlens_q": [[0, 100, 200]],
        "cu_seqlens_kv": [[0, 200, 400]],
        "seqused_q": [[100, 100]],
        "seqused_kv": [[200, 200]],
        "max_seqlen_q": [100],
        "max_seqlen_kv": [200],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BNSD"],
    },
    "BNSD_B4_QS64_KVS256_Nq4_Nkv2_D128_SP0": {
        "B": [4],
        "N_q": [4],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 64, 128, 192, 256]],
        "cu_seqlens_kv": [[0, 256, 512, 768, 1024]],
        "seqused_q": [[64, 64, 64, 64]],
        "seqused_kv": [[256, 256, 256, 256]],
        "max_seqlen_q": [64],
        "max_seqlen_kv": [256],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BNSD"],
    },
    "BNSD_B1_QS2000_KVS320_Nq4_Nkv1_D128_SP0": {
        "B": [1],
        "N_q": [4],
        "N_kv": [1],
        "D": [128],
        "cu_seqlens_q": [[0, 2000]],
        "cu_seqlens_kv": [[0, 320]],
        "seqused_q": [[2000]],
        "seqused_kv": [[320]],
        "max_seqlen_q": [2000],
        "max_seqlen_kv": [320],
        "mask_mode": [0],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BNSD"],
    },
    "BNSD_B3_QS32_KVS64_Nq8_Nkv8_D128_SP3": {
        "B": [3],
        "N_q": [8],
        "N_kv": [8],
        "D": [128],
        "cu_seqlens_q": [[0, 32, 64, 96]],
        "cu_seqlens_kv": [[0, 64, 128, 192]],
        "seqused_q": [[32, 32, 32]],
        "seqused_kv": [[64, 64, 64]],
        "max_seqlen_q": [32],
        "max_seqlen_kv": [64],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [True],
        "input_layout": ["BNSD"],
    },
    "BNSD_B1_QS512_KVS1024_Nq56_Nkv2_D128_SP3": {
        "B": [1],
        "N_q": [56],
        "N_kv": [2],
        "D": [128],
        "cu_seqlens_q": [[0, 512]],
        "cu_seqlens_kv": [[0, 1024]],
        "seqused_q": [[512]],
        "seqused_kv": [[1024]],
        "max_seqlen_q": [512],
        "max_seqlen_kv": [1024],
        "mask_mode": [3],
        "q_scale_layout": ["BSND"],
        "p_scale": [1.0],
        "enable_lse": [False],
        "input_layout": ["BNSD"],
    },
}

CASES = expand_paramset_to_cases(TEST_PARAMS)
SKIP_CASES = set()
