/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include <iostream>
#include <gtest/gtest.h>
#include "../../../op_host/rotary_position_embedding3d_tiling.cpp"
#include "tiling_context_faker.h"
#include "tiling_case_executor.h"

using namespace std;

class RotaryPositionEmbedding3dTiling : public testing::Test {
public:
    string compile_info_string = R"({"hardware_info": {"BT_SIZE": 0, "load3d_constraints": "1",
                                                       "Intrinsic_fix_pipe_l0c2out": false,
                                                       "Intrinsic_data_move_l12ub": true,
                                                       "Intrinsic_data_move_l0c2ub": true,
                                                       "Intrinsic_data_move_out2l1_nd2nz": false,
                                                       "UB_SIZE": 196608, "L2_SIZE": 201326592, "L1_SIZE": 524288,
                                                       "L0A_SIZE": 65536, "L0B_SIZE": 65536, "L0C_SIZE": 131072,
                                                       "CORE_NUM": 24}
                                    })";

protected:
    static void SetUpTestCase()
    {
        std::cout << "RotaryPositionEmbedding3dTiling SetUp" << std::endl;
    }

    static void TearDownTestCase()
    {
        std::cout << "RotaryPositionEmbedding3dTiling TearDown" << std::endl;
    }
};

TEST_F(RotaryPositionEmbedding3dTiling, RotaryPositionEmbedding3d_fp16_001)
{
    struct RotaryPositionEmbedding3dCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara("RotaryPositionEmbedding3d",
                                              {
                                                  // input info
                                                  {{{2, 64, 4, 8}, {2, 64, 4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                                  {{{2, 64, 4, 8}, {2, 64, 4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              {
                                                  // output info
                                                  {{{2, 64, 4, 8}, {2, 64, 4, 8}}, ge::DT_FLOAT16, ge::FORMAT_ND},
                                              },
                                              {
                                                  // attr (no attributes)
                                              },
                                              &compileInfo);
    // Tiling key is generated by GET_TPL_TILING_KEY(ELEMENTWISE_TPL_SCH_MODE_0)
    // Tiling data: totalLength(4096), lastDim(8), tileNum(8)
    // Tiling key: fp16=1
    uint64_t expectTilingKey = 1;
    string expectTilingData = "4096 8 256 1 2 128 4 2 2 1 512 512 * * ";
    std::vector<size_t> expectWorkspaces = {16 * 1024 * 1024};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(RotaryPositionEmbedding3dTiling, RotaryPositionEmbedding3d_fp32_001)
{
    struct RotaryPositionEmbedding3dCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara("RotaryPositionEmbedding3d",
                                              {
                                                  // input info
                                                  {{{1, 32, 16}, {1, 32, 16}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                                  {{{1, 32, 16}, {1, 32, 16}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  // output info
                                                  {{{1, 32, 16}, {1, 32, 16}}, ge::DT_FLOAT, ge::FORMAT_ND},
                                              },
                                              {
                                                  // attr
                                              },
                                              &compileInfo);
    uint64_t expectTilingKey = 0;
    string expectTilingData = "512 16 32 1 1 32 8 4 4 1 64 64 * * ";
    std::vector<size_t> expectWorkspaces = {16 * 1024 * 1024};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}

TEST_F(RotaryPositionEmbedding3dTiling, RotaryPositionEmbedding3d_bf16_001)
{
    struct RotaryPositionEmbedding3dCompileInfo {
    } compileInfo;
    gert::TilingContextPara tilingContextPara("RotaryPositionEmbedding3d",
                                              {
                                                  // input info
                                                  {{{4, 8, 16, 32}, {4, 8, 16, 32}}, ge::DT_BF16, ge::FORMAT_ND},
                                                  {{{4, 8, 16, 32}, {4, 8, 16, 32}}, ge::DT_BF16, ge::FORMAT_ND},
                                              },
                                              {
                                                  // output info
                                                  {{{4, 8, 16, 32}, {4, 8, 16, 32}}, ge::DT_BF16, ge::FORMAT_ND},
                                              },
                                              {
                                                  // attr
                                              },
                                              &compileInfo);
    // Tiling key: bf16=2
    uint64_t expectTilingKey = 2;
    string expectTilingData = "16384 32 128 1 1 128 16 8 8 1 2048 2048 * * ";
    std::vector<size_t> expectWorkspaces = {16 * 1024 * 1024};
    ExecuteTestCase(tilingContextPara, ge::GRAPH_SUCCESS, expectTilingKey, expectTilingData, expectWorkspaces);
}
