/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include <gtest/gtest.h>
#include "test_allto_all_matmul_v2_api_ut_param.h"
#include "op_api_ut_common/tensor_desc.h"
#include "op_api_ut_common/op_api_ut.h"
#include "opdev/platform.h"

using namespace op;
using namespace std;

/*!
 * The public aclnn header (aclnnop/aclnn_allto_all_matmul_v2.h) is not yet
 * generated by the build, so the two-phase API is declared manually here.
 */
extern "C" aclnnStatus AlltoAllMatmulV2GetWorkspaceSize(
    const aclTensor *context, const aclTensor *x1, const aclTensor *x2, const aclTensor *biasOptional,
    const aclTensor *x1ScaleOptional, const aclTensor *x2ScaleOptional, const char *group, int64_t worldSize,
    int64_t hcclBufferSize, int64_t x1QuantMode, int64_t x2QuantMode, int64_t groupSize, const char *commMode,
    int64_t precisionMode, const aclTensor *output, const aclTensor *alltoAllOutOptional, uint64_t *workspaceSize,
    aclOpExecutor **executor);
extern "C" aclnnStatus AlltoAllMatmulV2(void *workspace, uint64_t workspaceSize, aclOpExecutor *executor,
                                        aclrtStream stream);

namespace AlltoAllMatmulV2UT {

class AclnnAlltoAllMatmulV2Test : public testing::TestWithParam<AlltoAllMatmulV2ApiUtParam> {
protected:
    static void SetUpTestCase()
    {
        std::cout << "AlltoAllMatmulV2 AclnnAlltoAllMatmulV2Test SetUp" << std::endl;
    }

    static void TearDownTestCase()
    {
        std::cout << "AlltoAllMatmulV2 AclnnAlltoAllMatmulV2Test TearDown" << std::endl;
    }
};

TEST_P(AclnnAlltoAllMatmulV2Test, param)
{
    auto param = GetParam();
    op::SetPlatformSocVersion(param.soc);
    aclTensor *context = param.context.GetViewDims().empty() ? nullptr : param.context.ToAclTypeRawPtr();
    aclTensor *x1 = param.x1.GetViewDims().empty() ? nullptr : param.x1.ToAclTypeRawPtr();
    aclTensor *x2 = param.x2.GetViewDims().empty() ? nullptr : param.x2.ToAclTypeRawPtr();
    aclTensor *bias = param.bias.GetViewDims().empty() ? nullptr : param.bias.ToAclTypeRawPtr();
    aclTensor *x1Scale = param.x1Scale.GetViewDims().empty() ? nullptr : param.x1Scale.ToAclTypeRawPtr();
    aclTensor *x2Scale = param.x2Scale.GetViewDims().empty() ? nullptr : param.x2Scale.ToAclTypeRawPtr();
    aclTensor *output = param.output.GetViewDims().empty() ? nullptr : param.output.ToAclTypeRawPtr();
    aclTensor *alltoAllOut = param.alltoAllOut.GetViewDims().empty() ? nullptr : param.alltoAllOut.ToAclTypeRawPtr();

    auto ut = OP_API_UT(
        AlltoAllMatmulV2,
        INPUT(context, x1, x2, bias, x1Scale, x2Scale, param.group.c_str(), param.worldSize, param.hcclBufferSize,
              param.x1QuantMode, param.x2QuantMode, param.groupSize, param.commMode.c_str(), param.precisionMode),
        OUTPUT(output, alltoAllOut));
    uint64_t workspace_size = 0;
    aclOpExecutor *executor = nullptr;
    auto aclnnRet = ut.TestGetWorkspaceSizeWithNNopbaseInner(&workspace_size, executor);
    if (param.expectResult == ACLNN_SUCCESS) {
        EXPECT_NE(ACLNN_ERR_PARAM_INVALID, aclnnRet);
        // Call execute to cover the AlltoAllMatmulV2 execute function (L163-177).
        // Only when GetWorkspaceSize succeeds do we have a valid executor.
        if (aclnnRet == ACLNN_SUCCESS && executor != nullptr) {
            auto execRet = AlltoAllMatmulV2(nullptr, workspace_size, executor, nullptr);
            // Stubs make execute succeed; error path L173-174 stays uncovered.
            EXPECT_EQ(ACLNN_SUCCESS, execRet);
        }
    } else {
        EXPECT_EQ(param.expectResult, aclnnRet);
    }
}

INSTANTIATE_TEST_SUITE_P(
    AlltoAllMatmulV2, AclnnAlltoAllMatmulV2Test,
    testing::ValuesIn(GetCasesFromCsv<AlltoAllMatmulV2ApiUtParam>(ReplaceFileExtension2Csv(__FILE__))),
    PrintCaseInfoString<AlltoAllMatmulV2ApiUtParam>);

// Cover defensive nullptr branches in AlltoAllMatmulV2GetWorkspaceSize that
// the parameterised CSV framework cannot trigger (it always passes non-null
// workspaceSize / executor pointers).
TEST(AclnnAlltoAllMatmulV2NullptrTest, NullWorkspaceSizeAndExecutor)
{
    op::SetPlatformSocVersion(op::SocVersion::ASCEND950);
    TensorDesc context({1, 2052}, ACL_INT32, ACL_FORMAT_ND);
    TensorDesc x1({57086, 1536}, ACL_FLOAT8_E4M3FN, ACL_FORMAT_ND);
    TensorDesc x2({9216, 3072}, ACL_FLOAT8_E4M3FN, ACL_FORMAT_ND);
    TensorDesc x1Scale({57086, 24, 2}, ACL_FLOAT8_E8M0, ACL_FORMAT_ND);
    TensorDesc x2Scale({9216, 48, 2}, ACL_FLOAT8_E8M0, ACL_FORMAT_ND);
    TensorDesc output({28543, 9216}, ACL_BF16, ACL_FORMAT_ND);
    TensorDesc alltoAllOut({28543, 3072}, ACL_FLOAT8_E4M3FN, ACL_FORMAT_ND);

    // workspaceSize == nullptr  → covers L97
    aclOpExecutor *executor = nullptr;
    auto ret1 = AlltoAllMatmulV2GetWorkspaceSize(context.ToAclTypeRawPtr(), x1.ToAclTypeRawPtr(), x2.ToAclTypeRawPtr(),
                                                 nullptr, x1Scale.ToAclTypeRawPtr(), x2Scale.ToAclTypeRawPtr(), "group",
                                                 2, 0, 6, 6, 4295032864, "aiv_urma", 0, output.ToAclTypeRawPtr(),
                                                 alltoAllOut.ToAclTypeRawPtr(), nullptr, &executor);
    EXPECT_EQ(ACLNN_ERR_PARAM_NULLPTR, ret1);

    // executor == nullptr → covers L99
    uint64_t workspaceSize = 0;
    auto ret2 = AlltoAllMatmulV2GetWorkspaceSize(context.ToAclTypeRawPtr(), x1.ToAclTypeRawPtr(), x2.ToAclTypeRawPtr(),
                                                 nullptr, x1Scale.ToAclTypeRawPtr(), x2Scale.ToAclTypeRawPtr(), "group",
                                                 2, 0, 6, 6, 4295032864, "aiv_urma", 0, output.ToAclTypeRawPtr(),
                                                 alltoAllOut.ToAclTypeRawPtr(), &workspaceSize, nullptr);
    EXPECT_EQ(ACLNN_ERR_PARAM_NULLPTR, ret2);
}

// Cover the AlltoAllMatmulV2 execute function (L163-177) which the CSV-driven
// parameterised tests never call.  The stubbed NnopbaseSetHcclServerType and
// NnopbaseRunWithWorkspace make it safe to call with nullptr executor/workspace.
TEST(AclnnAlltoAllMatmulV2ExecuteTest, ExecuteCoversExecuteFunc)
{
    // AlltoAllMatmulV2 calls NnopbaseSetHcclServerType (stubbed no-op) then
    // aclnnInnerAlltoAllMatmulV2.  With nullptr executor the inner function's
    // NnopbaseGetUnContExecutor returns aclInExecutor=nullptr, inContWsSize=0,
    // the workspaceSize check passes (0 < 0 is false), and the stubbed
    // NnopbaseRunWithWorkspace returns OK → execute returns ACLNN_SUCCESS.
    auto execRet = AlltoAllMatmulV2(nullptr, 0, nullptr, nullptr);
    EXPECT_EQ(ACLNN_SUCCESS, execRet);
}

} // namespace AlltoAllMatmulV2UT
