#!/usr/bin/python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

import torch

# 定义测试参数组合
TEST_PARAMS = {
    "swa_decode": {
        "testcase_name": ["swa_decode"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "S2": [8193],
        "T1": [1],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "block_num1": [None],
        "block_size1": [128],
        "cu_seqlens_q": [[0, 1]],
        "seqused_ori_kv": [[8193]],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["SWA"],
        "q_datarange": ["[-2, 2]"],
        "ori_kv_datarange": ["[-2, 2]"],
        "cmp_kv_datarange": ["[-2, 2]"],
    },
    "test_swa_decode_pa": {
        "testcase_name": ["test_swa_decode_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "S2": [1024],
        "T1": [1],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "block_num1": [8],
        "block_size1": [128],
        "cu_seqlens_q": [[0, 1]],
        "seqused_ori_kv": [[1024]],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["SWA"],
    },
    "hca_tnd": {
        "testcase_name": ["hca_tnd"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "S2": [18],
        "T1": [1],
        "T2": [18],
        "T3": [4],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_ori_kv": [[0, 18]],
        "cu_seqlens_cmp_kv": [[0, 4]],
        "seqused_cmp_kv": [[4]],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["HCA"],
    },
    "csa_decode": {
        "testcase_name": ["csa_decode"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "S2": [4],
        "T1": [1],
        "T2": [4],
        "T3": [1],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_ori_kv": [[0, 4]],
        "cu_seqlens_cmp_kv": [[0, 1]],
        "cmp_residual_kv": [[0]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "csa_decode_pa": {
        "testcase_name": ["csa_decode_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "S2": [1024],
        "T1": [1],
        "T2": [1024],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [4],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 1]],
        "seqused_ori_kv": [[1024]],
        "seqused_cmp_kv": [[256]],
        "cmp_residual_kv": [[0]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "csa_g64_test_decode": {
        "testcase_name": ["csa_g64_test_decode"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [2],
        "S1": [1],
        "S2": [2050],
        "T1": [2],
        "T2": [4100],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 1, 2]],
        "cu_seqlens_ori_kv": [[0, 2050, 4100]],
        "cu_seqlens_cmp_kv": [[0, 512, 1024]],
        "seqused_ori_kv": [[2050, 2050]],
        "seqused_cmp_kv": [[512, 512]],
        "cmp_residual_kv": [[2, 2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "csa_g128_test_decode_B1": {
        "testcase_name": ["csa_g128_test_decode_B1"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "S2": [2050],
        "T1": [1],
        "T2": [2050],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 1]],
        "cu_seqlens_ori_kv": [[0, 2050]],
        "cu_seqlens_cmp_kv": [[0, 512]],
        "seqused_ori_kv": [[2050]],
        "seqused_cmp_kv": [[512]],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "csa_g128_test_decode_B16": {
        "testcase_name": ["csa_g128_test_decode_B16"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [16],
        "S1": [1],
        "S2": [128],
        "T1": [16],
        "T2": [128],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]],
        "seqused_ori_kv": [
            [
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
                128,
            ]
        ],
        "seqused_cmp_kv": [
            [32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
        ],
        "cmp_residual_kv": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],  # 残差
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["CSA"],
    },
    "csa_g64_test_prefill": {
        "testcase_name": ["csa_g64_test_prefill"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [2],
        "S2": [2050],
        "T1": [2],
        "T2": [2050],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],  # cmp_topk
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 2]],
        "cu_seqlens_ori_kv": [[0, 2050]],
        "cu_seqlens_cmp_kv": [[0, 512]],
        "seqused_ori_kv": [[2050]],
        "seqused_cmp_kv": [[512]],
        "cmp_residual_kv": [[2]],  # 残差 cmp_residual_kv
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],  # != 1
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],  # == 3
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "csa_g128_test_prefill": {
        "testcase_name": ["csa_g128_test_prefill"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [16],
        "S2": [640],
        "T1": [16],
        "T2": [640],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [10],
        "block_num2": [5],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 16]],
        "cu_seqlens_ori_kv": [[0, 640]],
        "cu_seqlens_cmp_kv": [[0, 160]],
        "seqused_ori_kv": [[640]],
        "seqused_cmp_kv": [[160]],
        "cmp_residual_kv": [[0]],  # 残差
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "csa_g128_test_prefill_padding": {
        "testcase_name": ["csa_g128_test_prefill_padding"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [16],
        "S2": [38],
        "T1": [16],
        "T2": [38],
        "T3": [9],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "cu_seqlens_q": [[0, 16]],
        "cu_seqlens_ori_kv": [[0, 38]],
        "cu_seqlens_cmp_kv": [[0, 9]],
        "seqused_q": [[10]],
        "seqused_ori_kv": [[22]],
        "seqused_cmp_kv": [[5]],
        "cmp_residual_kv": [[2]],  # 残差
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "csa_g128_test_prefill_TND": {
        "testcase_name": ["csa_g128_test_prefill_TND"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [16],
        "S2": [38],
        "T1": [16],
        "T2": [38],
        "T3": [9],  # TND且cmp
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "cu_seqlens_q": [[0, 16]],
        "cu_seqlens_ori_kv": [[0, 38]],
        "cu_seqlens_cmp_kv": [[0, 9]],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "cmp_csa_g64_test_prefill": {
        "testcase_name": ["cmp_csa_g64_test_prefill"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [38],
        "T1": [38],
        "T2": [166],
        "S2": [166],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "seqused_q": [[38]],
        "seqused_ori_kv": [[166]],
        "seqused_cmp_kv": [[41]],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
    },
    "ori_sparse_tnd_pa": {
        "testcase_name": ["ori_sparse_tnd_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [2],
        "S1": [1],
        "S2": [100],
        "T1": [2],
        "N1": [64, 128],
        "N2": [1],
        "D": [512],
        "K1": [50],
        "block_num1": [None],
        "block_size1": [128],
        "cu_seqlens_q": [[0, 1, 2]],
        "seqused_ori_kv": [[100, 100]],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0, 3, 4],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["ORI_SPARSE"],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "random_seq": [True],
    },
    "ori_sparse_bsnd_bsnd": {
        "testcase_name": ["ori_sparse_bsnd_bsnd"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [11],
        "S1": [3],
        "S2": [1001],
        "N1": [64, 128],
        "N2": [1],
        "D": [512],
        "K1": [50],
        "block_num1": [None],
        "block_size1": [None],
        "cu_seqlens_q": [None],
        "seqused_q": [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]],
        "seqused_ori_kv": [
            [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001]
        ],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0, 3, 4],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["ORI_SPARSE"],
        "ori_kv_topk_mode": ["random"],
        "cmp_kv_topk_mode": ["random"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "random_seq": [True],
    },
    "ori_sparse_tnd_tnd": {
        "testcase_name": ["ori_sparse_tnd_tnd"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [11],
        "S1": [3],
        "S2": [1001],
        "T1": [33],
        "T2": [11 * 1001],
        "N1": [64, 128],
        "N2": [1],
        "D": [512],
        "K1": [50],
        "block_num1": [None],
        "block_size1": [None],
        "cu_seqlens_q": [[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33]],
        "cu_seqlens_ori_kv": [
            [0, 1001, 2002, 3003, 4004, 5005, 6006, 7007, 8008, 9009, 10010, 11011]
        ],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0, 3, 4],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["ORI_SPARSE"],
        "ori_kv_topk_mode": ["random"],
        "cmp_kv_topk_mode": ["random"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "random_seq": [True],
    },
    "ori_sparse_bsnd_pa": {
        "testcase_name": ["ori_sparse_bsnd_pa"],
        "layout_q": ["BSND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [7],
        "S1": [3],
        "S2": [7777],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K1": [512],
        "K": [0],
        "block_num1": [None],
        "block_size1": [128],
        "seqused_q": [[3, 3, 3, 3, 3, 3, 3]],
        "seqused_ori_kv": [[7777, 7777, 7777, 7777, 7777, 7777, 7777]],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0, 3, 4],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["ORI_SPARSE"],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
    },
    "ori_cmp_sparse_tnd_pa": {
        "testcase_name": ["ori_cmp_sparse_tnd_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "S2": [1024],
        "T1": [1],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K1": [512],
        "K": [512],
        "block_num1": [None],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0, 3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["ORI_CMP_SPARSE"],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
    },
    "ori_cmp_sparse_bsnd_pa": {
        "testcase_name": ["ori_cmp_sparse_bsnd_pa"],
        "layout_q": ["BSND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [1],
        "S2": [1024],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K1": [512],
        "K": [512],
        "block_num1": [65],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[1]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0, 3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["ORI_CMP_SPARSE"],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
    },
    "smla_prefill_pro": {
        "testcase_name": [None],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [4096],
        "S2": [8192],
        "T1": [4096],
        "T2": [8192],
        "T3": [2048],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [1024],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
        "cmp_kv_topk_mode": ["fullK"],
        "cmp_sparse_indices_mode": ["full"],
    },
    "smla_prefill_flash": {
        "testcase_name": [None],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [1],
        "S1": [4096],
        "S2": [8192],
        "T1": [4096],
        "T2": [8192],
        "T3": [2048],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "template_mode": ["CSA"],
        "cmp_kv_topk_mode": ["fullK"],
        "cmp_sparse_indices_mode": ["full"],
    },
    "load_4096_swa_tnd_pa": {
        "testcase_name": ["bc_load_4096_swa_tnd_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [2],
        "S1": [2],
        "S2": [4096],
        "T1": [4],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "block_num1": [None],
        "block_size1": [128],
        "cu_seqlens_q": [[0, 2, 4]],
        "seqused_ori_kv": [[4096, 4096]],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["SWA"],
        "seqused_q": [[2, 2]],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_8192_hca_tnd_tnd": {
        "testcase_name": ["bc_load_8192_hca_tnd_tnd"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [2],
        "S1": [2],
        "S2": [6554],
        "T1": [4],
        "T2": [13108],
        "T3": [3276],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "cu_seqlens_q": [[0, 2, 4]],
        "cu_seqlens_ori_kv": [[0, 6554, 13108]],
        "cu_seqlens_cmp_kv": [[0, 1638, 3276]],
        "seqused_cmp_kv": [[1638, 1638]],
        "cmp_residual_kv": [[2, 2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [3],
        "cmp_mask_mode": [3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["HCA"],
        "seqused_ori_kv": [[6554, 6554]],
        "block_num1": [None],
        "block_num2": [None],
        "seqused_q": [[2, 2]],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_2048_csa_bsnd_bsnd": {
        "testcase_name": ["bc_load_2048_csa_bsnd_bsnd"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [2],
        "S1": [2],
        "T1": [None],
        "T2": [None],
        "S2": [1639],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [409],
        "seqused_q": [[2, 2]],
        "seqused_ori_kv": [[1639, 1639]],
        "seqused_cmp_kv": [[409, 409]],
        "cmp_residual_kv": [[3, 3]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["CSA"],
        "T3": [None],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_5120_ori_sparse_bsnd_pa": {
        "testcase_name": ["bc_load_5120_ori_sparse_bsnd_pa"],
        "layout_q": ["BSND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "B": [2],
        "S1": [2],
        "S2": [5120],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K1": [5120],
        "K": [0],
        "block_num1": [None],
        "block_size1": [128],
        "seqused_q": [[2, 2]],
        "seqused_ori_kv": [[5120, 5120]],
        "softmax_scale": [0.04419417],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["ORI_SPARSE"],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "cmp_mask_mode": [0],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_4096_ori_cmp_sparse_tnd_pa": {
        "testcase_name": ["bc_load_4096_ori_cmp_sparse_tnd_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.bfloat16],
        "cmp_kv_type": [torch.bfloat16],
        "B": [2],
        "S1": [2],
        "S2": [3277],
        "T1": [4],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K1": [3277],
        "K": [819],
        "block_num1": [None],
        "block_num2": [17],
        "block_size1": [128],
        "block_size2": [128],
        "cu_seqlens_q": [[0, 2, 4]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "return_softmax_lse": [False],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "template_mode": ["ORI_CMP_SPARSE"],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "seqused_ori_kv": [[3277, 3277]],
        "seqused_cmp_kv": [[819, 819]],
        "cmp_residual_kv": [None],
        "seqused_q": [[2, 2]],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
}

# 按需选择要启用的测试参数（例如默认启用所有）
ENABLED_PARAMS = [
    # {**TEST_PARAMS[key], "testcase_name": [key]} for key in TEST_PARAMS.keys()
    TEST_PARAMS["ori_sparse_tnd_pa"],
]
