/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file allto_all_matmul_tiling_key.h
 * \brief tiling_key
 */
#ifndef ALLTO_ALL_MATMUL_TILING_KEY_H
#define ALLTO_ALL_MATMUL_TILING_KEY_H

#include <ascendc/host_api/tiling/template_argument.h>

// 量化组合模式
#define NON_QUANT_MODE 0
// KC_QUANT量化模式，其中FP8E4M3代表X1经过动态量化后的数据类型
#define KC_QUANT_FP8E5M2_MODE 1
#define KC_QUANT_FP8E4M3_MODE 2
#define MX_QUANT_MODE 3
// bias的数据类型
#define DTYPE_BIAS_SAME_WITH_X 0
#define DTYPE_BIAS_FP32 1
// 通信方式
#define ALL2ALL_COMM_TYPE_CCU 0
#define ALL2ALL_COMM_TYPE_AICPU 1
// add_bias 分核模式 (仅非量化+有bias时生效, 0=关闭/无bias)
#define ADDBIAS_OFF 0
#define ADDBIAS_M_SPLIT 1
#define ADDBIAS_N_SPLIT 2
#define ADDBIAS_MN_SPLIT 3

// 模板参数范围声明
ASCENDC_TPL_ARGS_DECL(AlltoAllMatmul,
                      ASCENDC_TPL_UINT_DECL(QUANTMODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, NON_QUANT_MODE,
                                            KC_QUANT_FP8E4M3_MODE, KC_QUANT_FP8E5M2_MODE, MX_QUANT_MODE),
                      ASCENDC_TPL_BOOL_DECL(X2TRANSPOSE, 0, 1),
                      ASCENDC_TPL_UINT_DECL(DTYPEBIAS, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, DTYPE_BIAS_SAME_WITH_X,
                                            DTYPE_BIAS_FP32),
                      ASCENDC_TPL_BOOL_DECL(ISSMALLK, 0, 1),
                      ASCENDC_TPL_UINT_DECL(COMMTYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, ALL2ALL_COMM_TYPE_CCU,
                                            ALL2ALL_COMM_TYPE_AICPU),
                      ASCENDC_TPL_BOOL_DECL(USING_APACE_IMPL, 0, 1),
                      ASCENDC_TPL_UINT_DECL(ADDBIASSPLITMODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, ADDBIAS_OFF,
                                            ADDBIAS_M_SPLIT, ADDBIAS_N_SPLIT, ADDBIAS_MN_SPLIT), );

// 模板参数组合
// 用于调用GET_TPL_TILING_KEY获取TilingKey时，接口内部校验TilingKey是否合法
ASCENDC_TPL_SEL(
    // NON_QUANT_MODE: X2TRANSPOSE(0,1) x DTYPEBIAS(0,1) x ISSMALLK(0) x COMMTYPE(0,1)
    //                  x USING_APACE_IMPL(0) x ADDBIASSPLITMODE(0,1,2,3)
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
                         ASCENDC_TPL_UINT_SEL(QUANTMODE, ASCENDC_TPL_UI_LIST, NON_QUANT_MODE),
                         ASCENDC_TPL_BOOL_SEL(X2TRANSPOSE, 0, 1),
                         ASCENDC_TPL_UINT_SEL(DTYPEBIAS, ASCENDC_TPL_UI_LIST, DTYPE_BIAS_SAME_WITH_X, DTYPE_BIAS_FP32),
                         ASCENDC_TPL_BOOL_SEL(ISSMALLK, 0),
                         ASCENDC_TPL_UINT_SEL(COMMTYPE, ASCENDC_TPL_UI_LIST, ALL2ALL_COMM_TYPE_CCU,
                                              ALL2ALL_COMM_TYPE_AICPU),
                         ASCENDC_TPL_BOOL_SEL(USING_APACE_IMPL, 0),
                         ASCENDC_TPL_UINT_SEL(ADDBIASSPLITMODE, ASCENDC_TPL_UI_LIST, ADDBIAS_OFF, ADDBIAS_M_SPLIT,
                                              ADDBIAS_N_SPLIT, ADDBIAS_MN_SPLIT)),
    // KC_QUANT_FP8E4M3_MODE: USING_APACE_IMPL(0), ADDBIASSPLITMODE 恒为 OFF
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
                         ASCENDC_TPL_UINT_SEL(QUANTMODE, ASCENDC_TPL_UI_LIST, KC_QUANT_FP8E4M3_MODE),
                         ASCENDC_TPL_BOOL_SEL(X2TRANSPOSE, 0, 1),
                         ASCENDC_TPL_UINT_SEL(DTYPEBIAS, ASCENDC_TPL_UI_LIST, DTYPE_BIAS_FP32),
                         ASCENDC_TPL_BOOL_SEL(ISSMALLK, 0, 1),
                         ASCENDC_TPL_UINT_SEL(COMMTYPE, ASCENDC_TPL_UI_LIST, ALL2ALL_COMM_TYPE_CCU,
                                              ALL2ALL_COMM_TYPE_AICPU),
                         ASCENDC_TPL_BOOL_SEL(USING_APACE_IMPL, 0),
                         ASCENDC_TPL_UINT_SEL(ADDBIASSPLITMODE, ASCENDC_TPL_UI_LIST, ADDBIAS_OFF)),
    // KC_QUANT_FP8E5M2_MODE: USING_APACE_IMPL(0), ADDBIASSPLITMODE 恒为 OFF
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
                         ASCENDC_TPL_UINT_SEL(QUANTMODE, ASCENDC_TPL_UI_LIST, KC_QUANT_FP8E5M2_MODE),
                         ASCENDC_TPL_BOOL_SEL(X2TRANSPOSE, 0, 1),
                         ASCENDC_TPL_UINT_SEL(DTYPEBIAS, ASCENDC_TPL_UI_LIST, DTYPE_BIAS_FP32),
                         ASCENDC_TPL_BOOL_SEL(ISSMALLK, 0, 1),
                         ASCENDC_TPL_UINT_SEL(COMMTYPE, ASCENDC_TPL_UI_LIST, ALL2ALL_COMM_TYPE_CCU,
                                              ALL2ALL_COMM_TYPE_AICPU),
                         ASCENDC_TPL_BOOL_SEL(USING_APACE_IMPL, 0),
                         ASCENDC_TPL_UINT_SEL(ADDBIASSPLITMODE, ASCENDC_TPL_UI_LIST, ADDBIAS_OFF)),
    // MX_QUANT_MODE + USING_APACE_IMPL=0: arch35主线pipeline, MIX_AIC_1_2, ADDBIASSPLITMODE 恒为 OFF
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(QUANTMODE, ASCENDC_TPL_UI_LIST, MX_QUANT_MODE), ASCENDC_TPL_BOOL_SEL(X2TRANSPOSE, 0, 1),
        ASCENDC_TPL_UINT_SEL(DTYPEBIAS, ASCENDC_TPL_UI_LIST, DTYPE_BIAS_FP32), ASCENDC_TPL_BOOL_SEL(ISSMALLK, 0),
        ASCENDC_TPL_UINT_SEL(COMMTYPE, ASCENDC_TPL_UI_LIST, ALL2ALL_COMM_TYPE_CCU, ALL2ALL_COMM_TYPE_AICPU),
        ASCENDC_TPL_BOOL_SEL(USING_APACE_IMPL, 0),
        ASCENDC_TPL_UINT_SEL(ADDBIASSPLITMODE, ASCENDC_TPL_UI_LIST, ADDBIAS_OFF)),
    // MX_QUANT_MODE + USING_APACE_IMPL=1: hcomm纯C通信, AIC_ONLY, ADDBIASSPLITMODE 恒为 OFF
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(QUANTMODE, ASCENDC_TPL_UI_LIST, MX_QUANT_MODE), ASCENDC_TPL_BOOL_SEL(X2TRANSPOSE, 0, 1),
        ASCENDC_TPL_UINT_SEL(DTYPEBIAS, ASCENDC_TPL_UI_LIST, DTYPE_BIAS_FP32), ASCENDC_TPL_BOOL_SEL(ISSMALLK, 0),
        ASCENDC_TPL_UINT_SEL(COMMTYPE, ASCENDC_TPL_UI_LIST, ALL2ALL_COMM_TYPE_CCU, ALL2ALL_COMM_TYPE_AICPU),
        ASCENDC_TPL_BOOL_SEL(USING_APACE_IMPL, 1),
        ASCENDC_TPL_UINT_SEL(ADDBIASSPLITMODE, ASCENDC_TPL_UI_LIST, ADDBIAS_OFF)));

#endif // ALLTO_ALL_MATMUL_TILING_KEY_H
